services:
  - type: web
    name: weather-app-backend
    env: python
    plan: free
    buildCommand: poetry install
    startCommand: poetry run gunicorn app:app
    rootDir: backend
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: weather-app-frontend
    env: node
    plan: free
    runtime: nodejs14  # Usa una versión más antigua de Node.js
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    rootDir: frontend
    envVars:
      - key: NODE_ENV
        value: production
