services:
  - type: web
    name: weather-app-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: weather-app-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    rootDir: frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
