services:
  - type: web
    name: weathernow-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: OPENWEATHER_API_KEY
        value: "tu_clave_api_aqui"
    autoDeploy: true
    rootDir: backend
  - type: web
    name: weathernow-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    plan: free
    autoDeploy: true
    rootDir: frontend
